sudo: required
language: bash
services:
  - docker

# define the build matrix
env:
  global:
    - RUN_TESTS: false

matrix:
  include:
    # Ubuntu 18.04 bionic (gcc)
    - name: "bionic: gcc"
      os: linux
      env: >
        BUILD_FLAVOR=ubuntu
        TOOLCHAIN=gcc-cxx17
        DOCKER_TAG=ubuntu-lts-gcc

    # Ubuntu 19.04 disco (gcc)
    - name: "disco: gcc"
      os: linux
      env: >
        BUILD_FLAVOR=ubuntu
        DOCKER_TAG=ubuntu-rolling-gcc
        TOOLCHAIN=gcc-cxx17

    # Ubuntu 19.04 disco (clang)
    - name: "disco: clang"
      os: linux
      env: >
        BUILD_FLAVOR=ubuntu
        DOCKER_TAG=ubuntu-rolling-clang
        TOOLCHAIN=clang-cxx17

    # Fedora rawhide
    - name: "fedora rawhide"
      os: linux
      env: >
        BUILD_FLAVOR=fedora
        TOOLCHAIN=gcc-cxx17
        DOCKER_TAG=fedora-rawhide-gcc

before_install:
  - docker pull openblack/openblack:$DOCKER_TAG

script:
 - |
  # run the respective .travis.<distro>.sh script
  docker run \
  -e BUILD_FLAVOR="$BUILD_FLAVOR" \
  -e TOOLCHAIN="$TOOLCHAIN" \
  -e RUN_TESTS="$RUN_TESTS" \
  -v ${HOME}:/root \
  -v ${PWD}:/usr/src/openblack \
  -w /usr/src/openblack \
  -it openblack/openblack:$DOCKER_TAG ci/travis.$BUILD_FLAVOR.sh

