name: CI
on: [push]
jobs:
  build:
    name: Build openblack
    runs-on: ubuntu-latest
    container:
      image: openblack/openblack:ubuntu-rolling-gcc
    steps:
    - uses: actions/checkout@v1

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_TOOLCHAIN_FILE="/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" \
        -DOPENBLACK_BGFX_USE_SYSTEM_DEPS=ON \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .